name = "cloudflare-d1-test"
main = "src/index.ts"
compatibility_date = "2024-05-23"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "rentiful"
database_id = "756c2412-5166-409e-977b-e5748c1f5578"
